-- Öffentliche Rückmeldungen: Schreiben erlaubt, Lesen und Ändern gesperrt.
create table if not exists public.reader_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  category text not null check (char_length(category) between 3 and 80),
  message text not null check (char_length(message) between 10 and 5000),
  story_version text not null check (char_length(story_version) between 1 and 20)
);

alter table public.reader_feedback enable row level security;
revoke all on table public.reader_feedback from anon, authenticated;
revoke all on sequence public.reader_feedback_id_seq from anon, authenticated;
drop policy if exists "Public may submit reader feedback" on public.reader_feedback;

-- Nur die Edge Function darf schreiben. Anonyme Browser erhalten keinen
-- direkten Tabellenzugriff. Die Hashes sind kurzlebige Pseudonyme zum Schutz
-- gegen Massen-Einträge; rohe IP-Adressen werden nicht gespeichert.
create table if not exists public.feedback_rate_limits (
  id bigint generated by default as identity primary key,
  client_hash text not null check (client_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now()
);
create index if not exists feedback_rate_limits_client_time_idx
on public.feedback_rate_limits (client_hash, created_at desc);
alter table public.feedback_rate_limits enable row level security;
revoke all on table public.feedback_rate_limits from anon, authenticated;
revoke all on sequence public.feedback_rate_limits_id_seq from anon, authenticated;

-- Unabhängig von neuen Einsendungen stündlich abgelaufene Prüfwerte löschen.
create extension if not exists pg_cron;
do $$
declare
  existing_job bigint;
begin
  select jobid into existing_job
  from cron.job
  where jobname = 'purge-feedback-rate-limits';
  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;
end;
$$;
select cron.schedule(
  'purge-feedback-rate-limits',
  '17 * * * *',
  $$delete from public.feedback_rate_limits where created_at < now() - interval '24 hours'$$
);

create or replace function public.submit_reader_feedback(
  p_client_hash text,
  p_category text,
  p_message text,
  p_story_version text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  recent_count integer;
  last_submission timestamptz;
begin
  if p_client_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid client identifier' using errcode = '22023';
  end if;
  if p_category not in (
    'Allgemeiner Eindruck',
    'Stimmigkeit der Geschichte',
    'Technische oder fachliche Frage',
    'Idee für die Fortsetzung'
  ) then
    raise exception 'invalid category' using errcode = '22023';
  end if;
  if char_length(trim(p_message)) not between 10 and 5000 then
    raise exception 'invalid message length' using errcode = '22023';
  end if;
  if p_story_version !~ '^[0-9]+\.[0-9]+$' or char_length(p_story_version) > 20 then
    raise exception 'invalid story version' using errcode = '22023';
  end if;

  -- Serialisiert gleichzeitige Anfragen desselben pseudonymen Clients.
  perform pg_advisory_xact_lock(hashtext(p_client_hash));
  delete from public.feedback_rate_limits
  where created_at < now() - interval '24 hours';

  select count(*), max(created_at)
  into recent_count, last_submission
  from public.feedback_rate_limits
  where client_hash = p_client_hash
    and created_at >= now() - interval '15 minutes';

  if last_submission is not null and last_submission > now() - interval '15 seconds' then
    raise exception 'feedback submitted too quickly' using errcode = 'P0001';
  end if;
  if recent_count >= 3 then
    raise exception 'feedback rate limit exceeded' using errcode = 'P0001';
  end if;

  insert into public.feedback_rate_limits (client_hash) values (p_client_hash);
  insert into public.reader_feedback (category, message, story_version)
  values (p_category, trim(p_message), p_story_version);
end;
$$;
revoke all on function public.submit_reader_feedback(text, text, text, text) from public;
grant execute on function public.submit_reader_feedback(text, text, text, text) to service_role;

-- Absichtlich keine Tabellen-Policy für anonyme oder angemeldete Besucher.

-- Explizite Positivliste der Benutzer, die neue Versionen veröffentlichen dürfen.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.admin_users enable row level security;
revoke all on table public.admin_users from anon, authenticated;

create or replace function public.is_story_admin()
returns boolean language sql stable security definer
set search_path = public
as $$
  select
    coalesce(auth.jwt() ->> 'aal', 'aal1') = 'aal2'
    and exists (select 1 from public.admin_users where user_id = auth.uid())
$$;
revoke all on function public.is_story_admin() from public;
grant execute on function public.is_story_admin() to authenticated;

-- Genau eine öffentlich lesbare Zeile beschreibt die jeweils aktuelle Ausgabe.
create table if not exists public.story_release (
  id text primary key check (id = 'current'),
  version text not null,
  display_date text not null,
  page_count integer not null check (page_count between 1 and 1000),
  published_at timestamptz not null default now()
);
insert into public.story_release (id, version, display_date, page_count)
values ('current', '1.11', '30. August 2026', 46)
on conflict (id) do nothing;
alter table public.story_release enable row level security;
revoke all on table public.story_release from anon, authenticated;
grant select on table public.story_release to anon, authenticated;
grant update on table public.story_release to authenticated;
drop policy if exists "Anyone may read current release" on public.story_release;
create policy "Anyone may read current release" on public.story_release for select to anon, authenticated using (true);
drop policy if exists "Admins may update current release" on public.story_release;
create policy "Admins may update current release" on public.story_release for update to authenticated using (public.is_story_admin()) with check (public.is_story_admin());

-- Stabile öffentliche Dateipfade; nur freigeschaltete Administratoren schreiben.
insert into storage.buckets (id, name, public)
values ('story', 'story', true)
on conflict (id) do update set public = true;

-- Upserts of existing objects require SELECT in addition to INSERT/UPDATE.
drop policy if exists "Story admins may read" on storage.objects;
create policy "Story admins may read" on storage.objects for select to authenticated
using (bucket_id = 'story' and public.is_story_admin());
drop policy if exists "Story admins may upload" on storage.objects;
create policy "Story admins may upload" on storage.objects for insert to authenticated
with check (bucket_id = 'story' and public.is_story_admin());
drop policy if exists "Story admins may replace" on storage.objects;
create policy "Story admins may replace" on storage.objects for update to authenticated
using (bucket_id = 'story' and public.is_story_admin())
with check (bucket_id = 'story' and public.is_story_admin());
