create table if not exists public.reader_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  category text not null check (char_length(category) between 3 and 80),
  message text not null check (char_length(message) between 10 and 5000),
  story_version text not null check (char_length(story_version) between 1 and 20)
);

alter table public.reader_feedback enable row level security;
revoke all on table public.reader_feedback from anon, authenticated;
grant insert on table public.reader_feedback to anon;
grant usage, select on sequence public.reader_feedback_id_seq to anon;

drop policy if exists "Public may submit reader feedback" on public.reader_feedback;
create policy "Public may submit reader feedback"
on public.reader_feedback for insert to anon
with check (
  char_length(category) between 3 and 80
  and char_length(message) between 10 and 5000
  and char_length(story_version) between 1 and 20
);

-- Absichtlich keine SELECT-, UPDATE- oder DELETE-Policy für anonyme Besucher.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.admin_users enable row level security;
revoke all on table public.admin_users from anon, authenticated;

create or replace function public.is_story_admin()
returns boolean language sql stable security definer
set search_path = public
as $$ select exists (select 1 from public.admin_users where user_id = auth.uid()) $$;
revoke all on function public.is_story_admin() from public;
grant execute on function public.is_story_admin() to authenticated;

create table if not exists public.story_release (
  id text primary key check (id = 'current'),
  version text not null,
  display_date text not null,
  page_count integer not null check (page_count between 1 and 1000),
  published_at timestamptz not null default now()
);
insert into public.story_release (id, version, display_date, page_count)
values ('current', '1.10', '29. August 2026', 46)
on conflict (id) do nothing;
alter table public.story_release enable row level security;
revoke all on table public.story_release from anon, authenticated;
grant select on table public.story_release to anon, authenticated;
grant update on table public.story_release to authenticated;
drop policy if exists "Anyone may read current release" on public.story_release;
create policy "Anyone may read current release" on public.story_release for select to anon, authenticated using (true);
drop policy if exists "Admins may update current release" on public.story_release;
create policy "Admins may update current release" on public.story_release for update to authenticated using (public.is_story_admin()) with check (public.is_story_admin());

insert into storage.buckets (id, name, public)
values ('story', 'story', true)
on conflict (id) do update set public = true;

drop policy if exists "Story admins may upload" on storage.objects;
create policy "Story admins may upload" on storage.objects for insert to authenticated
with check (bucket_id = 'story' and public.is_story_admin());
drop policy if exists "Story admins may replace" on storage.objects;
create policy "Story admins may replace" on storage.objects for update to authenticated
using (bucket_id = 'story' and public.is_story_admin())
with check (bucket_id = 'story' and public.is_story_admin());
